import Link from "next/link";
import { redirect } from "next/navigation";
import { adminClient, getCustomUser } from "@/lib/custom-auth";
import { JLPT_LEVELS, type JlptLevel } from "@/lib/jlpt-level";
import { updateStudyLevel } from "./actions";

type TestRow = { id: number; title: string; description: string | null; level: string; duration_minutes: number; is_premium: boolean; is_active: boolean };
type AttemptRow = { id: number; test_id: number | null; score: number; total_points: number; percentage: number | null; status: string; started_at: string; completed_at: string | null };

const protocolDefaults = [
  ["Full Mock Exam", "REAL ENVIRONMENT", "assignment", "Complete practice under realistic timed exam conditions.", "Strict sectional cutoffs applied", "red"],
  ["Quick Practice", "SPEED CALIBRATION", "bolt", "Short focused practice with immediate answer feedback.", "Instant answer verification", "green"],
  ["Custom Exam", "ADAPTIVE ENGINE", "tune", "Build a focused test from the available question bank.", "Choose your target sections", "slate"],
];

export default async function DashboardPage() {
  const user = await getCustomUser();
  if (!user) redirect("/login");
  const client = adminClient();
  const selectedLevel = (JLPT_LEVELS.includes(user.target_level as JlptLevel) ? user.target_level : "N5") as JlptLevel;
  const [{ data: attemptRows }, { data: testRows }, { data: questionRows }] = await Promise.all([
    client.from("attempts").select("id, test_id, score, total_points, percentage, status, started_at, completed_at").eq("user_id", user.id).order("started_at", { ascending: false }).limit(30),
    client.from("tests").select("id, title, description, level, duration_minutes, is_premium, is_active").eq("is_active", true).eq("level", selectedLevel).order("created_at", { ascending: false }),
    client.from("questions").select("id, test_id"),
  ]);
  const tests = (testRows ?? []) as TestRow[];
  const levelTestIds = new Set(tests.map((test) => test.id));
  const attempts = ((attemptRows ?? []) as AttemptRow[]).filter((attempt) => attempt.test_id !== null && levelTestIds.has(attempt.test_id));
  const questions = questionRows ?? [];
  const completed = attempts.filter((attempt) => attempt.status === "completed");
  const activeAttempt = attempts.find((attempt) => attempt.status === "in_progress");
  const activeTest = tests.find((test) => test.id === activeAttempt?.test_id) ?? tests[0];
  const percentages = completed.map((attempt) => Number(attempt.percentage ?? 0));
  const average = percentages.length ? Math.round(percentages.reduce((sum, value) => sum + value, 0) / percentages.length) : 0;
  const best = percentages.length ? Math.max(...percentages) : 0;
  const passRate = percentages.length ? Math.round((percentages.filter((value) => value >= 60).length / percentages.length) * 100) : 0;
  const questionCount = (testId: number | undefined) => questions.filter((question) => question.test_id === testId).length;

  const chartValues = completed.slice(0, 8).reverse().map((attempt) => Number(attempt.score ?? Math.round(Number(attempt.percentage ?? 0) * 1.8)));
  const chartPoints = (chartValues.length ? chartValues : [0]).map((value, index, values) => ({ x: values.length === 1 ? 70 : 70 + (595 * index) / (values.length - 1), y: 210 - (Math.min(Math.max(value, 0), 180) / 180) * 180, value }));
  const chartPolyline = chartPoints.map((point) => `${point.x},${point.y}`).join(" ");
  const chartArea = `${chartPolyline} 665,210 70,210`;
  const heatmap = Array.from({ length: 12 }, (_, week) => Array.from({ length: 5 }, (_, day) => {
    const target = new Date();
    target.setDate(target.getDate() - ((11 - week) * 7 + day));
    return Math.min(4, completed.filter((attempt) => new Date(attempt.started_at).toDateString() === target.toDateString()).length);
  }));
  const protocols = protocolDefaults.map((defaults, index) => {
    const test = tests[index];
    return { title: test?.title ?? defaults[0], label: defaults[1], icon: defaults[2], description: test?.description ?? defaults[3], detailOne: `${questionCount(test?.id) || 0} questions · ${test?.duration_minutes ?? 0} minutes`, detailTwo: defaults[4], tone: defaults[5], href: test ? `/simulation/${test.id}` : "/tests" };
  });

  return <div className="mx-auto w-full max-w-[1560px] space-y-8 px-5 py-8 lg:px-10 lg:py-10">
    <section className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Study target</p><h1 className="mt-1 text-xl font-bold text-slate-900">JLPT {selectedLevel}</h1><p className="mt-1 text-sm text-slate-500">Dashboard and mock exams are filtered to this level.</p></div><form action={updateStudyLevel} className="flex items-center gap-2"><label htmlFor="study-level" className="sr-only">JLPT level</label><select id="study-level" name="level" defaultValue={selectedLevel} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-900">{JLPT_LEVELS.map((level) => <option key={level} value={level}>{level}</option>)}</select><button type="submit" className="rounded-lg bg-[var(--red)] px-4 py-2 text-sm font-bold text-white">Change level</button></form></section>
    <section className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:p-8"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div className="max-w-3xl space-y-5"><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-[0.12em]"><span className="rounded bg-[var(--red)] px-3 py-2 text-white">{activeAttempt ? "Resume session" : "Start a session"}</span><span className="rounded border border-slate-200 bg-slate-100 px-3 py-2 text-slate-700">{activeAttempt ? "In-flight" : "Ready"}</span><span className="text-slate-500">{activeTest?.title ?? "No active test available"}</span></div><div><h1 className="text-3xl font-bold tracking-tight text-slate-900">{activeAttempt ? "Continue your simulation" : "Build your next result"}</h1><p className="mt-2 text-slate-600">{activeTest?.description ?? "Choose an available practice test to begin your JLPT session."}</p></div><div className="space-y-2"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[0.12em]"><span className="text-slate-500">Overall test dispatch</span><span className="text-[var(--red)]">{activeAttempt ? "In progress" : `${completed.length} completed`}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--red)]" style={{ width: activeAttempt ? "42%" : completed.length ? "100%" : "0%" }} /></div></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><span className="block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">Question bank</span><span className="mt-2 block text-xl font-bold text-slate-900">{questionCount(activeTest?.id)} <small className="font-normal text-slate-400">questions</small></span></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><span className="block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">Current level</span><span className="mt-2 block text-sm font-semibold text-slate-800">{activeTest?.level ?? "N5"}</span></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><span className="block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">Duration</span><span className="mt-2 block font-mono text-xl font-bold text-[var(--red)]">{activeTest?.duration_minutes ?? 0} min</span></div></div></div><div className="flex min-w-[220px] flex-col gap-3"><Link href={activeTest ? `/simulation/${activeTest.id}` : "/tests"} className="rounded-xl bg-[var(--red)] px-5 py-3 text-center text-sm font-bold text-white shadow-md transition hover:bg-[var(--red-dark)]">{activeAttempt ? "Continue exam" : "Browse tests"} →</Link><Link href="/tests" className="rounded-xl border border-slate-200 bg-slate-100 px-5 py-3 text-center text-sm font-semibold text-slate-700 transition hover:bg-slate-200">View all tests</Link></div></div></section>


    <section id="analytics" className="scroll-mt-24 space-y-4"><div className="flex items-end justify-between gap-3"><div><h2 className="text-2xl font-bold tracking-tight text-slate-900">Testing protocols</h2><p className="mt-1 text-sm text-slate-600">Available tests loaded from your practice library.</p></div><span className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{tests.length} tests loaded</span></div><div className="grid gap-5 md:grid-cols-3">{protocols.map((protocol) => <article key={protocol.title} className="group flex flex-col justify-between rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="space-y-5"><div className="flex items-center justify-between"><span className={`grid size-12 place-items-center rounded-xl text-2xl ${protocol.tone === "red" ? "bg-red-50 text-[var(--red)]" : protocol.tone === "green" ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-slate-700"}`}>{protocol.icon === "assignment" ? "▣" : protocol.icon === "bolt" ? "↯" : "⌘"}</span><span className="rounded border border-slate-200 bg-slate-50 px-2 py-1 text-[10px] font-bold tracking-[0.08em] text-slate-600">{protocol.label}</span></div><div><h3 className="text-xl font-bold text-slate-900">{protocol.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{protocol.description}</p></div><div className="space-y-2 text-xs font-semibold uppercase tracking-[0.08em] text-slate-600"><p><span className="mr-2 text-[var(--red)]">•</span>{protocol.detailOne}</p><p><span className="mr-2 text-emerald-600">•</span>{protocol.detailTwo}</p></div></div><Link href={protocol.href} className={`mt-7 rounded-lg px-4 py-3 text-center text-sm font-bold transition ${protocol.tone === "red" ? "bg-[var(--red)] text-white hover:bg-[var(--red-dark)]" : "border border-slate-200 bg-slate-100 text-slate-800 hover:bg-slate-200"}`}>Open test →</Link></article>)}</div></section>
    <section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold tracking-tight text-slate-900">Performance telemetry</h2><span className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Live account data</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Average score", `${average}%`, "Completed simulations"], ["Highest score", `${best}%`, best ? "Personal record" : "No score yet"], ["Exams completed", String(completed.length).padStart(2, "0"), "All-time account total"], ["Current pass rate", `${passRate}%`, passRate >= 60 ? "Passing trend" : "Keep practicing"]].map(([label, value, note]) => <div key={label} className="flex min-h-36 flex-col justify-between rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">{label}</span><div className="mt-5"><span className="text-4xl font-bold tracking-tight text-slate-900">{value}</span><span className="ml-2 text-sm font-semibold text-slate-400">{note}</span></div>{label === "Current pass rate" && <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${passRate}%` }} /></div>}</div>)}</div></section>

    <section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold text-slate-900">Recent exam simulations</h2><p className="mt-1 text-sm text-slate-500">Your latest completed and in-progress attempts.</p></div><Link href="/tests" className="text-sm font-semibold text-[var(--red)]">View all tests →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-y border-slate-200 bg-slate-50 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500"><th className="px-4 py-3">Exam</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Score</th><th className="px-4 py-3">Result</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{attempts.length ? attempts.slice(0, 6).map((attempt) => { const test = tests.find((item) => item.id === attempt.test_id); const percentage = Number(attempt.percentage ?? 0); return <tr key={attempt.id} className="group hover:bg-slate-50"><td className="px-4 py-4 font-semibold text-slate-900">{test?.title ?? `Simulation #${attempt.id}`}</td><td className="px-4 py-4 text-xs font-semibold uppercase text-slate-500">{attempt.status.replace("_", " ")}</td><td className="px-4 py-4 font-bold">{attempt.score} <span className="font-normal text-slate-400">/ {attempt.total_points}</span></td><td className="px-4 py-4"><span className={`rounded-full border px-2 py-1 text-xs font-bold ${percentage >= 60 ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{attempt.status === "completed" ? `${percentage}%` : "Pending"}</span></td><td className="px-4 py-4 text-xs text-slate-500">{new Date(attempt.started_at).toLocaleDateString()}</td><td className="px-4 py-4 text-right"><Link href={attempt.status === "completed" ? `/results/${attempt.id}` : test ? `/simulation/${test.id}` : "/tests"} className="font-semibold text-[var(--red)]">{attempt.status === "completed" ? "View result" : "Continue"} →</Link></td></tr>; }) : <tr><td colSpan={6} className="px-4 py-10 text-center text-sm text-slate-500">No simulations yet. Open a test above to create your first attempt.</td></tr>}</tbody></table></div></section>

    <section id="history" className="scroll-mt-24 space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold text-slate-900">Recent exam simulations</h2><p className="mt-1 text-sm text-slate-500">Your latest completed and in-progress attempts.</p></div><Link href="/tests" className="text-sm font-semibold text-[var(--red)]">View all tests →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-y border-slate-200 bg-slate-50 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500"><th className="px-4 py-3">Exam</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Score</th><th className="px-4 py-3">Result</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{attempts.length ? attempts.slice(0, 6).map((attempt) => { const test = tests.find((item) => item.id === attempt.test_id); const percentage = Number(attempt.percentage ?? 0); return <tr key={attempt.id} className="group hover:bg-slate-50"><td className="px-4 py-4 font-semibold text-slate-900">{test?.title ?? `Simulation #${attempt.id}`}</td><td className="px-4 py-4 text-xs font-semibold uppercase text-slate-500">{attempt.status.replace("_", " ")}</td><td className="px-4 py-4 font-bold">{attempt.score} <span className="font-normal text-slate-400">/ {attempt.total_points}</span></td><td className="px-4 py-4"><span className={`rounded-full border px-2 py-1 text-xs font-bold ${percentage >= 60 ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{attempt.status === "completed" ? `${percentage}%` : "Pending"}</span></td><td className="px-4 py-4 text-xs text-slate-500">{new Date(attempt.started_at).toLocaleDateString()}</td><td className="px-4 py-4 text-right"><Link href={attempt.status === "completed" ? `/results/${attempt.id}` : test ? `/simulation/${test.id}` : "/tests"} className="font-semibold text-[var(--red)]">{attempt.status === "completed" ? "View result" : "Continue"} →</Link></td></tr>; }) : <tr><td colSpan={6} className="px-4 py-10 text-center text-sm text-slate-500">No simulations yet. Open a test above to create your first attempt.</td></tr>}</tbody></table></div></section>
    <section className="relative overflow-hidden rounded-2xl border border-red-200/80 bg-gradient-to-r from-red-50/70 via-white to-slate-50 p-6 shadow-sm lg:p-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-center"><div className="max-w-3xl space-y-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[var(--red)]"><span className="size-2 rounded-full bg-[var(--red)]" />Recommended next challenge</div><h2 className="text-3xl font-bold tracking-tight text-slate-900">{tests[0]?.title ?? "No recommendation available"}</h2><div className="flex flex-wrap gap-2"><span className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs font-semibold">{questionCount(tests[0]?.id)} Questions</span><span className="rounded-md border border-slate-200 bg-white px-3 py-2 text-xs font-semibold">{tests[0]?.duration_minutes ?? 0} Minutes</span><span className="rounded-md border border-red-200 bg-white px-3 py-2 text-xs font-bold text-[var(--red)]">{tests[0]?.is_premium ? "Premium test" : "Available now"}</span></div><p className="text-sm leading-6 text-slate-600">{tests[0]?.description ?? "Add an active test to your library to receive a personalized recommendation."}</p></div>{tests[0] && <Link href={`/simulation/${tests[0].id}`} className="shrink-0 rounded-xl bg-[var(--red)] px-6 py-4 text-center text-sm font-bold text-white shadow-md transition hover:bg-[var(--red-dark)]">Start simulation →</Link>}</div></section>

    <section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-900">Score progress over time</h2><p className="mt-1 text-sm text-slate-500">Computed from your completed attempts.</p></div><div className="flex gap-3 text-xs font-semibold"><span className="text-[var(--red)]">● Score</span><span className="text-emerald-600">━ Pass cutoff</span></div></div><div className="h-64 rounded-xl border border-slate-100 bg-slate-50/70 p-3"><svg className="h-full w-full" viewBox="0 0 700 240" preserveAspectRatio="none"><line x1="40" x2="680" y1="130" y2="130" stroke="#10b981" strokeDasharray="6 3" strokeWidth="1.5" /><text x="8" y="134" fill="#059669" fontSize="11">95</text><line x1="40" x2="680" y1="20" y2="20" stroke="#e2e8f0" strokeDasharray="4 4" /><line x1="40" x2="680" y1="180" y2="180" stroke="#e2e8f0" strokeDasharray="4 4" /><polyline fill="none" points={chartPolyline} stroke="#dc2626" strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" /><polygon fill="#dc262622" points={chartArea} />{chartPoints.map((point) => <circle key={`${point.x}-${point.value}`} cx={point.x} cy={point.y} r="5" fill="white" stroke="#dc2626" strokeWidth="2.5" />)}{chartPoints.map((point, index) => <text key={`label-${point.x}`} x={point.x - 10} y="228" fill={index === chartPoints.length - 1 ? "#dc2626" : "#64748b"} fontSize="11">#{index + 1}</text>)}</svg></div><div className="flex items-center justify-between text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500"><span>Activity cadence · past 12 weeks</span><span>Less · More</span></div><div className="flex gap-1.5 overflow-x-auto">{heatmap.map((week, index) => <div key={index} className="flex flex-col gap-1.5">{week.map((level, day) => <span key={day} className={`size-3.5 rounded-sm ${level === 0 ? "border border-slate-200 bg-slate-100" : level === 1 ? "bg-red-200" : level === 2 ? "bg-red-300" : level === 3 ? "bg-red-400" : "bg-red-600"}`} />)}</div>)}</div>{!completed.length && <p className="text-sm text-slate-500">Complete a simulation to populate your score history and activity cadence.</p>}</section>
  </div>;
}
