import Link from "next/link";

const modes = [
  { title: "Yearly Exam", eyebrow: "PAST EXAM PRACTICE", description: "Practice a complete JLPT N5 exam from one selected year, in its original order and section structure.", meta: "2007 - 2024", href: "/mock-exam/yearly", tone: "red" },
  { title: "Custom Exam", eyebrow: "RANDOMIZED QUESTION BANK", description: "Generate a new JLPT-style exam from the available question bank. Every attempt can be different.", meta: "Mixed source years", href: "/mock-exam/custom", tone: "green" },
];

export default function MockExamPage() {
  return <div className="mx-auto w-full max-w-5xl px-5 py-10 lg:py-16"><Link href="/dashboard" className="text-sm font-semibold text-slate-500 hover:text-slate-900">← Back to dashboard</Link><div className="mt-10 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--red)]">JLPT N5 mock exam</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Choose your mock exam.</h1><p className="mt-4 text-lg leading-8 text-slate-600">Both modes use the same JLPT-style exam experience with structured sections, timing, answer saving, and results.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2">{modes.map((mode) => <article key={mode.title} className="flex min-h-[310px] flex-col justify-between rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div><div className={`grid size-12 place-items-center rounded-xl text-2xl ${mode.tone === "red" ? "bg-red-50 text-[var(--red)]" : "bg-emerald-50 text-emerald-600"}`}>{mode.tone === "red" ? "▣" : "↯"}</div><p className="mt-7 text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{mode.eyebrow}</p><h2 className="mt-2 text-2xl font-bold text-slate-950">{mode.title}</h2><p className="mt-3 leading-7 text-slate-600">{mode.description}</p></div><div className="mt-7 flex items-center justify-between gap-4"><span className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold uppercase tracking-[0.1em] text-slate-600">{mode.meta}</span><Link href={mode.href} className={`rounded-xl px-5 py-3 text-sm font-bold text-white ${mode.tone === "red" ? "bg-[var(--red)] hover:bg-[var(--red-dark)]" : "bg-emerald-600 hover:bg-emerald-700"}`}>Choose mode →</Link></div></article>)}</div></div>;
}
