import Link from "next/link";

const features = [["01", "Vocabulary", "Build a sharper base with everyday Japanese."], ["02", "Grammar", "Turn particles and patterns into instinct."], ["03", "Reading", "Get comfortable finding meaning at speed."], ["04", "Listening", "Train your ear with focused practice."], ["05", "Exam timer", "Practice with the gentle pressure of the real thing."], ["06", "Instant results", "See your progress as soon as you finish."]];

export default function Home() { return <div>
  <section className="paper-grid overflow-hidden border-b border-[var(--line)]"><div className="mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-16 md:grid-cols-[1.1fr_.9fr] md:items-center md:pb-28 md:pt-24"><div className="fade-up"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.2em] text-[var(--red)]">Japanese practice, made human</p><h1 className="max-w-2xl text-5xl font-semibold leading-[1.05] tracking-tight sm:text-7xl">Pass N5 with a little more <span className="text-[var(--red)]">confidence.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[var(--ink-muted)]">A focused simulation space for vocabulary, grammar, reading and listening. Practice smarter. Pass JLPT N5.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/simulation/free-n5" className="rounded-full bg-[var(--red)] px-6 py-3 font-medium text-white shadow-lg shadow-red-200 transition hover:bg-[var(--red-dark)]">Start free test <span className="ml-2">→</span></Link><Link href="/premium" className="rounded-full border border-[var(--foreground)] bg-white px-6 py-3 font-medium transition hover:bg-[var(--foreground)] hover:text-white">Get premium</Link></div></div><div className="fade-up-delay relative mx-auto w-full max-w-sm"><div className="rotate-2 border border-[#cbd9cc] bg-[#dcecdf] p-3 shadow-xl"><div className="bg-[var(--cream)] p-6"><div className="mb-12 flex justify-between text-xs font-semibold uppercase tracking-widest text-[var(--red)]"><span>今日の練習</span><span>01 / 04</span></div><p className="text-3xl font-semibold leading-snug">わたしは毎朝<br/><span className="text-[var(--red)]">______</span> を飲みます。</p><div className="mt-10 space-y-3 text-sm"><div className="border border-[#d9cdbd] bg-white px-4 py-3">A. 水</div><div className="border border-[#d9cdbd] px-4 py-3">B. 本</div><div className="border border-[#d9cdbd] px-4 py-3">C. 車</div></div></div></div><div className="absolute -bottom-5 -left-5 -rotate-6 bg-[var(--red)] px-4 py-3 text-sm font-semibold text-white shadow-lg">Small steps, daily.</div></div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-20"><div className="mb-10 max-w-xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-[var(--red)]">The toolkit</p><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Everything you need to make N5 feel familiar.</h2></div><div className="grid border-l border-t border-[var(--line)] sm:grid-cols-2 lg:grid-cols-3">{features.map(([number, title, copy]) => <div key={title} className="border-b border-r border-[var(--line)] bg-white p-6"><span className="text-xs text-[var(--ink-muted)]">{number}</span><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{copy}</p></div>)}</div></section>
  <section className="border-y border-[var(--line)] bg-[#eef4ef]"><div className="mx-auto max-w-6xl px-5 py-20"><div className="grid gap-6 md:grid-cols-2"><div className="border border-[var(--line)] bg-white p-7"><span className="rounded-full bg-[var(--mint)] px-3 py-1 text-xs font-semibold text-[#317052]">FREE PLAN</span><h3 className="mt-6 text-2xl font-semibold">Start with the essentials.</h3><ul className="mt-5 space-y-3 text-sm text-[var(--ink-muted)]"><li>✓ 1 free simulation</li><li>✓ Limited question set</li><li>✓ Instant basic result</li></ul><Link href="/simulation/free-n5" className="mt-8 inline-block font-semibold text-[var(--red)]">Try it now →</Link></div><div className="border border-[var(--foreground)] bg-[var(--foreground)] p-7 text-white"><span className="rounded-full bg-[#f4d8a0] px-3 py-1 text-xs font-semibold text-[#6f4b11]">PREMIUM</span><div className="mt-6 flex items-end justify-between gap-4"><h3 className="text-2xl font-semibold">The full practice room.</h3><p className="text-right text-2xl font-semibold">10,000 <span className="text-sm font-normal text-[#bdc8c1]">MMK</span></p></div><ul className="mt-5 space-y-3 text-sm text-[#c9d4cd]"><li>✓ 10+ simulations and full N5 bank</li><li>✓ Listening tests and explanations</li><li>✓ Unlimited practice and history</li></ul><Link href="/premium" className="mt-8 inline-block font-semibold text-[#f4d8a0]">See premium →</Link></div></div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-20 text-center"><p className="text-2xl font-semibold sm:text-3xl">Your next correct answer starts here.</p><Link href="/register" className="mt-7 inline-block rounded-full bg-[var(--foreground)] px-6 py-3 font-medium text-white transition hover:bg-[var(--red-dark)]">Create your free account</Link></section>
</div>; }
