-- Step 1: database foundation for yearly and generated custom mock exams.
-- Store only original or otherwise legally licensed question content.

create table if not exists public.exam_templates (
  id bigint generated by default as identity primary key,
  level text not null,
  name text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_template_parts (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.exam_templates(id) on delete cascade,
  section_type text not null check (section_type in ('moji_goi', 'grammar_reading', 'listening')),
  question_type text not null,
  required_question_count integer not null check (required_question_count > 0),
  order_number integer not null check (order_number > 0),
  unique (template_id, order_number),
  unique (template_id, section_type, question_type)
);

create table if not exists public.yearly_exams (
  id bigint generated by default as identity primary key,
  level text not null,
  year integer not null check (year between 2007 and 2024),
  title text not null,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  unique (level, year)
);

alter table public.tests add column if not exists level text not null default 'N5';
alter table public.tests add column if not exists source_year integer check (source_year is null or source_year between 2007 and 2024);
alter table public.tests add column if not exists yearly_exam_id bigint references public.yearly_exams(id) on delete set null;

alter table public.questions add column if not exists level text not null default 'N5';
alter table public.questions add column if not exists source_year integer check (source_year is null or source_year between 2007 and 2024);
alter table public.questions add column if not exists section_type text check (section_type in ('moji_goi', 'grammar_reading', 'listening'));
alter table public.questions add column if not exists question_type text;
alter table public.questions add column if not exists passage_id text;
alter table public.questions add column if not exists group_id text;
alter table public.questions add column if not exists is_active boolean not null default true;

create table if not exists public.yearly_exam_questions (
  id bigint generated by default as identity primary key,
  yearly_exam_id bigint not null references public.yearly_exams(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  section_order integer not null check (section_order > 0),
  question_order integer not null check (question_order > 0),
  unique (yearly_exam_id, question_id),
  unique (yearly_exam_id, question_order)
);

create table if not exists public.generated_exams (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  template_id bigint not null references public.exam_templates(id),
  level text not null default 'N5',
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.generated_exam_questions (
  id bigint generated by default as identity primary key,
  generated_exam_id uuid not null references public.generated_exams(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  section_order integer not null check (section_order > 0),
  question_order integer not null check (question_order > 0),
  unique (generated_exam_id, question_id),
  unique (generated_exam_id, question_order)
);

alter table public.attempts add column if not exists exam_mode text not null default 'legacy' check (exam_mode in ('legacy', 'yearly', 'custom'));
alter table public.attempts add column if not exists source_year integer check (source_year is null or source_year between 2007 and 2024);
alter table public.attempts add column if not exists generated_exam_id uuid references public.generated_exams(id) on delete set null;
alter table public.attempts add column if not exists submitted_at timestamptz;
alter table public.attempts add column if not exists total_score integer;

create index if not exists questions_generation_idx on public.questions (level, source_year, section_type, question_type) where is_active = true;
create index if not exists yearly_exam_questions_order_idx on public.yearly_exam_questions (yearly_exam_id, section_order, question_order);
create index if not exists generated_exam_questions_order_idx on public.generated_exam_questions (generated_exam_id, section_order, question_order);
create index if not exists attempts_mode_idx on public.attempts (user_id, exam_mode, started_at desc);

alter table public.exam_templates enable row level security;
alter table public.exam_template_parts enable row level security;
alter table public.yearly_exams enable row level security;
alter table public.yearly_exam_questions enable row level security;
alter table public.generated_exams enable row level security;
alter table public.generated_exam_questions enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create policy "active templates read" on public.exam_templates for select using (is_active or public.is_admin());
create policy "active template parts read" on public.exam_template_parts for select using (exists (select 1 from public.exam_templates t where t.id = template_id and (t.is_active or public.is_admin())));
create policy "published yearly exams read" on public.yearly_exams for select using (is_published or public.is_admin());
create policy "published yearly questions read" on public.yearly_exam_questions for select using (exists (select 1 from public.yearly_exams e where e.id = yearly_exam_id and (e.is_published or public.is_admin())));
create policy "own generated exams" on public.generated_exams for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "own generated questions" on public.generated_exam_questions for select using (exists (select 1 from public.generated_exams e where e.id = generated_exam_id and (e.user_id = auth.uid() or public.is_admin())));

create policy "admin templates" on public.exam_templates for all using (public.is_admin());
create policy "admin template parts" on public.exam_template_parts for all using (public.is_admin());
create policy "admin yearly exams" on public.yearly_exams for all using (public.is_admin());
create policy "admin yearly questions" on public.yearly_exam_questions for all using (public.is_admin());

comment on table public.exam_templates is 'Configurable exam structures; question counts belong here, not in frontend code.';
comment on table public.generated_exams is 'Immutable custom exam instance created on the server.';
comment on column public.questions.source_year is 'Year of the legally permitted source content, when applicable.';
comment on column public.questions.group_id is 'Keeps passage/listening questions that must stay together.';
